# Generated by Django 5.0.2 on 2024-02-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproduct',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_product', to='main_app.list'),
        ),
    ]
