# Generated by Django 5.0.2 on 2024-02-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_listproduct_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='personalization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
